version: '2'
services:
  pig-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: pig-mysql
    image: pig-mysql
    volumes:
      - /opt/sf-cloud/docker-db-data:/var/lib/mysql
    ports:
      - 3308:3306

  pig-redis:
    image: redis:6.0
    ports:
      - 6380:6379
    restart: always
    container_name: pig-redis
    hostname: pig-redis

  pig-register:
    build:
      context: ./pig-register
    restart: always
    ports:
      - 8848:8848
    container_name: pig-register
    hostname: pig-register
    image: pig-register
    depends_on:
      - pig-mysql
      - pig-redis

  pig-gateway:
    build:
      context: ./pig-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: pig-gateway
    hostname: pig-gateway
    image: pig-gateway
    depends_on:
      - pig-register

  pig-auth:
    build:
      context: ./pig-auth
    restart: always
    container_name: pig-auth
    hostname: pig-auth
    image: pig-auth
    ports:
      - 3000:3000
    depends_on:
      - pig-register


  pig-upms:
    build:
      context: ./pig-upms/pig-upms-biz
    restart: always
    container_name: pig-upms
    hostname: pig-upms
    image: pig-upms
    ports:
      - 4000:4000
    depends_on:
      - pig-gateway

#  pig-monitor:
#    build:
#      context: ./pig-visual/pig-monitor
#    restart: always
#    ports:
#      - 5001:5001
#    container_name: pig-monitor
#    hostname: pig-monitor
#    image: pig-monitor
#
#  pig-sentinel:
#    build:
#      context: ./pig-visual/pig-sentinel-dashboard
#    restart: always
#    image: pig-sentinel
#    container_name: pig-sentinel
#    ports:
#      - 5003:5003

  pig-codegen:
    build:
      context: ./pig-visual/pig-codegen
    restart: always
    container_name: pig-codegen
    hostname: pig-codegen
    image: pig-codegen

  sf-task:
    build:
      context: ./sf-task/sf-task-biz
    restart: always
    container_name: sf-task
    hostname: sf-task
    image: sf-task
