server:
  port: 4001

spring:
  application:
    name: pig-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties
---
spring:
  profiles: native
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1025/eureka
    registry-fetch-interval-seconds: 10

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@eureka:1025/eureka
