## spring security 配置
security:
  oauth2:
    ignore:
      urls:
        - /webjars/**
        - /v3/api-docs/**
        - /doc.html
        - /swagger-ui.html
        - /swagger-ui/**
        - /swagger-resources
        - /token/check_token
        - /error
        - /actuator/**
        - /code/**

# 前端密码登录解密密钥
gateway:
  encodeKey: thanks,pig4cloud

# 数据源
spring:
  data:
    redis:
      host: pigx-redis
      database: 9  #避免和微服务 PIGX 冲突
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://pig-mysql:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
  cache:
    type: redis

# 本地文件系统
file:
  local:
    enable: true
    basePath: /Users/lengleng/Downloads/img
