server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://123.206.129.162:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    
zipkin:
  collector:
    rabbitmq:
      addresses: 123.206.129.162:5682
      password: redis
      username: redis
      queue: zipkin
  storage:
    type: mysql